export const Al9ora2Array = [
  {
    id: 0,
    name: "أحمد الحواشي",
    path: "https://surahmp3.com/m/Ahmad-Alhawashi/",
    riwayat: ["hafs"],
  },
  {
    id: 1,
    name: "أحمد بن علي العجمي",
    path: "https://surahmp3.com/m/Ahmad-Bnali-Alajami/",
    riwayat: ["hafs"],
  },
  {
    id: 2,
    name: "أحمد سعود",
    path: "https://surahmp3.com/m/Ahmed-Saoud/",
    riwayat: ["hafs"],
  },
  {
    id: 3,
    name: "أحمد صابر",
    path: "https://surahmp3.com/m/Ahmed-Saber/",
    riwayat: ["hafs"],
  },
  {
    id: 4,
    name: "أحمد نعينع",
    path: "https://surahmp3.com/m/Ahmed-N3in3/",
    riwayat: ["hafs"],
  },
  {
    id: 5,
    name: "أكرم العلاقمي",
    path: "https://surahmp3.com/m/Akram-Alalakmi/",
    riwayat: ["hafs"],
  },
  {
    id: 6,
    name: "إبراهيم الأخضر",
    path: "https://surahmp3.com/m/Ibrahim-Alakhdar/",
    riwayat: ["hafs"],
  },
  {
    id: 7,
    name: "إبراهيم الجبرين",
    path: "https://surahmp3.com/m/Ibrahim-Aljabrin/",
    riwayat: ["hafs"],
  },
  {
    id: 8,
    name: "ابراهيم العسيري",
    path: "https://surahmp3.com/m/Ibrahim-Alossayri/",
    riwayat: ["hafs"],
  },
  {
    id: 9,
    name: "ادريس أبكر",
    path: "https://surahmp3.com/m/Idriss-Abkar/",
    riwayat: ["hafs"],
  },
  {
    id: 10,
    name: "الحسيني العزازي",
    path: "https://surahmp3.com/m/Alhsini-Al3zazi/",
    riwayat: ["mo3alam"],
  },
  {
    id: 11,
    name: "الزين محمد أحمد",
    path: "https://surahmp3.com/m/Alzain-Mohamed-Ahmed/",
    riwayat: ["hafs"],
  },
  {
    id: 12,
    name: "العشري عمران",
    path: "https://surahmp3.com/m/Alachri-Omran/",
    riwayat: ["hafs"],
  },
  {
    id: 13,
    name: "العيون الكوشي",
    path: "https://surahmp3.com/m/Layoun-Alkouchi/",
    riwayat: ["warsh"],
  },
  {
    id: 14,
    name: "القارئ ياسين",
    path: "https://surahmp3.com/m/Alkari-Yassine/",
    riwayat: ["warsh"],
  },
  {
    id: 15,
    name: "توفيق الصايغ",
    path: "https://surahmp3.com/m/Twfik-Assaygh/",
    riwayat: ["hafs"],
  },
  {
    id: 16,
    name: "جمال شاكر عبدالله",
    path: "https://surahmp3.com/m/Jamal-Chakir-Abdallah/",
    riwayat: ["hafs"],
  },
  {
    id: 17,
    name: "حمد الدغريري",
    path: "https://surahmp3.com/m/Hamad-Adghrizi/",
    riwayat: ["hafs"],
  },
  {
    id: 18,
    name: "خالد الجليل",
    path: "https://surahmp3.com/m/Khakid-Aljalil/",
    riwayat: ["hafs"],
  },
  {
    id: 19,
    name: "خالد القحطاني",
    path: "https://surahmp3.com/m/Khalid-Alkahtani/",
    riwayat: ["hafs"],
  },
  {
    id: 20,
    name: "خالد الوهيبي",
    path: "https://surahmp3.com/m/Khalid-Alwahbi/",
    riwayat: ["hafs"],
  },
  {
    id: 21,
    name: "خالد عبد الكافي",
    path: "https://surahmp3.com/m/Khalid-Abdelkafi/",
    riwayat: ["hafs"],
  },
  {
    id: 22,
    name: "خليفة الطنيجي",
    path: "https://surahmp3.com/m/Khalifa-Atniji/",
    riwayat: ["hafs"],
  },
  {
    id: 23,
    name: "داود حمزة",
    path: "https://surahmp3.com/m/Dawoud-Hamza/",
    riwayat: ["hafs"],
  },
  {
    id: 24,
    name: "رشيد إفراد",
    path: "https://surahmp3.com/m/Rachid-Ifrad/",
    riwayat: ["warsh"],
  },
  {
    id: 25,
    name: "رشيد بلعالية",
    path: "https://surahmp3.com/m/Rachid-Bl3alya/",
    riwayat: ["hafs", "warsh"],
  },
  {
    id: 26,
    name: "زكريا حمامة",
    path: "https://surahmp3.com/m/Zakaria-Hmama//",
    riwayat: ["hafs"],
  },
  {
    id: 27,
    name: "زكي داغستاني",
    path: "https://surahmp3.com/m/Zaki-Daghstani/",
    riwayat: ["hafs"],
  },
  {
    id: 28,
    name: "سامي الحسن",
    path: "https://surahmp3.com/m/Sami-Alhassan/",
    riwayat: ["hafs"],
  },
  {
    id: 29,
    name: "سامي الدوسري",
    path: "https://surahmp3.com/m/Sami-Adawsari/",
    riwayat: ["hafs"],
  },
  {
    id: 30,
    name: "سعد الغامدي",
    path: "https://surahmp3.com/m/Saad-Alghamidi/",
    riwayat: ["hafs"],
  },
  {
    id: 31,
    name: "سعود الشريم",
    path: "https://surahmp3.com/m/Saoud-Shrim/",
    riwayat: ["hafs"],
  },
  {
    id: 32,
    name: "سهل ياسين",
    path: "https://surahmp3.com/m/Sahl-Yassine/",
    riwayat: ["hafs"],
  },
  {
    id: 33,
    name: "سيد رمضان",
    path: "https://surahmp3.com/m/Sayid-Ramadan/",
    riwayat: ["hafs"],
  },
  {
    id: 34,
    name: "شعبان الصياد",
    path: "https://surahmp3.com/m/Chaaban-Assayad/",
    riwayat: ["hafs"],
  },
  {
    id: 35,
    name: "شيخ أبو بكر الشاطري",
    path: "https://surahmp3.com/m/Aboubakr-Achatiri/",
    riwayat: ["hafs"],
  },
  {
    id: 36,
    name: "شيرزاد عبد الرحمن طاهر",
    path: "https://surahmp3.com/m/Chirzad-Abdrahman-Tahir/",
    riwayat: ["hafs"],
  },
  {
    id: 37,
    name: "صابر عبد الحكم",
    path: "https://surahmp3.com/m/Saber-Abdelhakam/",
    riwayat: ["hafs"],
  },
  {
    id: 38,
    name: "صالح آل طالب",
    path: "https://surahmp3.com/m/Salih-Altaleb/",
    riwayat: ["hafs"],
  },
  {
    id: 39,
    name: "صالح الصاهود",
    path: "https://surahmp3.com/m/Salih-Assahod/",
    riwayat: ["hafs"],
  },
  {
    id: 40,
    name: "صالح الهبدان",
    path: "https://surahmp3.com/m/Salih-Alhabdan/",
    riwayat: ["hafs"],
  },
  {
    id: 41,
    name: "صلاح البدير",
    path: "https://surahmp3.com/m/Salah-Albdir/",
    riwayat: ["hafs"],
  },
  {
    id: 42,
    name: "صلاح الهاشم",
    path: "https://surahmp3.com/m/Salah-Alhachim/",
    riwayat: ["hafs", "9alon"],
  },
  {
    id: 43,
    name: "صلاح بو خاطر",
    path: "https://surahmp3.com/m/Salah-Boukhatr/",
    riwayat: ["hafs"],
  },
  {
    id: 44,
    name: "عادل ريان",
    path: "https://surahmp3.com/m/Adil-Rayan/",
    riwayat: ["hafs"],
  },
  {
    id: 45,
    name: "عبد البارئ الثبيتي",
    path: "https://surahmp3.com/m/Abd-Albari-Tbiti/",
    riwayat: ["hafs"],
  },
  {
    id: 46,
    name: "عبد البارئ محمد",
    path: "https://surahmp3.com/m/Abdlbari-Mohamed/",
    riwayat: ["hafs", "mo3alam"],
  },
  {
    id: 47,
    name: "عبد الباسط عبدالصمد",
    path: "https://surahmp3.com/m/Abdlbast-Abdsamad/",
    riwayat: ["hafs", "warsh", "mojawad"],
  },
  {
    id: 48,
    name: "عبد الرشيد صوفي",
    path: "https://surahmp3.com/m/Abdrachid-Sofi/",
    riwayat: ["hafs", "khalaf", "sousi"],
  },
  {
    id: 49,
    name: "عبد العزيز الأحمد",
    path: "https://surahmp3.com/m/Abdla3ziz-Alahmad/",
    riwayat: ["hafs"],
  },
  {
    id: 50,
    name: "عبد العزيز الزهراني",
    path: "https://surahmp3.com/m/Abdlaziz-Azahrani/",
    riwayat: ["hafs"],
  },
  {
    id: 51,
    name: "عبد الله البريمي",
    path: "https://surahmp3.com/m/Abdlah-Albrimi/",
    riwayat: ["hafs"],
  },
  {
    id: 52,
    name: "عبد الله البعيجان",
    path: "https://surahmp3.com/m/Abdlah-Alb3ijan/",
    riwayat: ["hafs"],
  },
  {
    id: 53,
    name: "عبد الله المطرود",
    path: "https://surahmp3.com/m/Abdlah-Almtrod/",
    riwayat: ["hafs"],
  },
  {
    id: 54,
    name: "عبد الله بصفر",
    path: "https://surahmp3.com/m/Abdelah-Bsfr/",
    riwayat: ["hafs"],
  },
  {
    id: 55,
    name: "عبد الله خياط",
    path: "https://surahmp3.com/m/Abdlah-Khyat/",
    riwayat: ["hafs"],
  },
  {
    id: 56,
    name: "عبد الله عواد الجهني",
    path: "https://surahmp3.com/m/Abdlah-Owad-Aljahni/",
    riwayat: ["hafs"],
  },
  {
    id: 57,
    name: "عبد الله غيلان",
    path: "https://surahmp3.com/m/Abdlah-Ghilan/",
    riwayat: ["hafs"],
  },
  {
    id: 58,
    name: "عبد المحسن الحارثي",
    path: "https://surahmp3.com/m/Abdlmohsin-Alhariti/",
    riwayat: ["hafs"],
  },
  {
    id: 59,
    name: "عبد المحسن العبيكان",
    path: "https://surahmp3.com/m/Abdlmohsin-Al3bikan/",
    riwayat: ["hafs"],
  },
  {
    id: 60,
    name: "عبد المحسن العسكر",
    path: "https://surahmp3.com/m/Abdlmohsin-Alaskr/",
    riwayat: ["hafs"],
  },
  {
    id: 61,
    name: "عبد المحسن القاسم",
    path: "https://surahmp3.com/m/Abdlmohsin-Alkasm/",
    riwayat: ["hafs"],
  },
  {
    id: 62,
    name: "عبد الهادي أحمد كناكري",
    path: "https://surahmp3.com/m/Abdlhadi-Ahmad-Knakri/",
    riwayat: ["hafs"],
  },
  {
    id: 63,
    name: "عبد الودود حنيف",
    path: "https://surahmp3.com/m/Abdalwadod-Hanif/",
    riwayat: ["hafs"],
  },
  {
    id: 64,
    name: "عبد الولي الأركاني",
    path: "https://surahmp3.com/m/Abd-Alwali-Alarkari/",
    riwayat: ["hafs"],
  },
  {
    id: 65,
    name: "عبدالرحمن السديس",
    path: "https://surahmp3.com/m/Abdrahman-Sudaysi/",
    riwayat: ["hafs"],
  },
  {
    id: 66,
    name: "علي أبو هاشم",
    path: "https://surahmp3.com/m/Ali-Abouhachim/",
    riwayat: ["hafs"],
  },
  {
    id: 67,
    name: "علي بن عبد الرحمن الحذيفي",
    path: "https://surahmp3.com/m/Ali-Bn-Abdrahman-Alhodayfi/",
    riwayat: ["hafs", "9alon"],
  },
  {
    id: 68,
    name: "علي جابر",
    path: "https://surahmp3.com/m/Ali-Jabir/",
    riwayat: ["hafs"],
  },
  {
    id: 69,
    name: "علي حجاج السويسي",
    path: "https://surahmp3.com/m/Ali-Hajaj-Aswissi/",
    riwayat: ["hafs"],
  },
  {
    id: 70,
    name: "عماد زهير حافظ",
    path: "https://surahmp3.com/m/Imad-Zohir-Hafid/",
    riwayat: ["hafs"],
  },
  {
    id: 71,
    name: "عمر القزابري",
    path: "https://surahmp3.com/m/Omar-Alkzabri/",
    riwayat: ["warsh"],
  },
  {
    id: 72,
    name: "فارس عباد",
    path: "https://surahmp3.com/m/Faris-Abad/",
    riwayat: ["hafs"],
  },
];
