export const Al9ora2Array = [
    { name: 'إبراهيم الأخضر', path: 'https://surahmp3.com/m/001.Ibrahim-Alakhdar/' },
    { name: 'إبراهيم الجبرين', path: 'https://surahmp3.com/m/002.Ibrahim-Aljabrin/' },
    { name: 'ابراهيم العسيري', path: 'https://surahmp3.com/m/003.Ibrahim-Alossayri/' },
    { name: 'شيخ أبو بكر الشاطري', path: 'https://surahmp3.com/m/004.Aboubakr-Achatiri/' },
    { name: 'أحمد بن علي العجمي', path: 'https://surahmp3.com/m/005.Ahmad-Bnali-Alajami/' },
    { name: 'أحمد الحواشي', path: 'https://surahmp3.com/m/006.Ahmad-Alhawashi/' },
    { name: 'أحمد سعود', path: 'https://surahmp3.com/m/007.Ahmed-Saoud/' },
    { name: 'أحمد صابر', path: 'https://surahmp3.com/m/008.Ahmed-Saber/' },
    { name: 'أحمد نعينع', path: 'https://surahmp3.com/m/009.Ahmed-N3in3/' },
    { name: 'أكرم العلاقمي', path: 'https://surahmp3.com/m/010.Akram-Alalakmi/' },
    { name: 'الحسيني العزازي', path: 'https://surahmp3.com/m/011.Alhsini-Al3zazi/' },
    { name: 'ادريس أبكر', path: 'https://surahmp3.com/m/012.Idriss-Abkar/' },
    { name: 'الزين محمد أحمد', path: 'https://surahmp3.com/m/013.Alzain-Mohamed-Ahmed/' },
    { name: 'القارئ ياسين', path: 'https://surahmp3.com/m/014.Alkar2-Yassine/' },
    { name: 'العشري عمران', path: 'https://surahmp3.com/m/015.Alachri-Imran/' },
    { name: 'العيون الكوشي', path: 'https://surahmp3.com/m/016.Layoun-Alkouchi/' },
    { name: 'توفيق الصايغ', path: 'https://surahmp3.com/m/017.Twfik-Assaygh/' },
    { name: 'جمال شاكر عبدالله', path: 'https://surahmp3.com/m/018.Jamal-Chakir-Abdallah/' },
    { name: 'حمد الدغريري', path: 'https://surahmp3.com/m/019.Hamad-Adghrizi/' },
    { name: 'خالد الجليل', path: 'https://surahmp3.com/m/020.Khakid-Aljalil/' },
    { name: 'خالد القحطاني', path: 'https://surahmp3.com/m/021.Khalid-Alkahtani/' },
    { name: 'خالد عبدالكافي', path: 'https://surahmp3.com/m/022.Khalid-Abdelkafi/' },
    { name: 'خالد الوهيبي', path: 'https://surahmp3.com/m/023.Khalid-Alwahbi/' },
    { name: 'خليفة الطنيجي', path: 'https://surahmp3.com/m/024.Khalifa-Atniji/' },
    //waiting ...
    { name: 'عبدالرحمن السديس', path: 'https://surahmp3.com/m/Abdrahman-Sudaysi/' },
    { name: 'هزاع البلوشي', path: 'https://surahmp3.com/m/Hazzaa-Albalouchi/' },
    { name: 'ماهر المعيقلي', path: 'https://surahmp3.com/m/Mahir-Almeikli/' },
    { name: 'محمود خليل الحصري', path: 'https://surahmp3.com/m/Mahmoud-Khalil-Alhusari/' },
    { name: 'محمد صديق المنشاوي', path: 'https://surahmp3.com/m/Mohamed-Sidik-Almnshawi/' },
    { name: 'ناصر القطامي', path: 'https://surahmp3.com/m/Nassir-Alkattami/' },
    { name: 'عمر القزابري', path: 'https://surahmp3.com/m/Omar-Alkzabri/' },
    { name: 'رعد محمد الكردي', path: 'https://surahmp3.com/m/Raad-Mohamed-Alkordi/' },
    { name: 'سعد الغامدي', path: 'https://surahmp3.com/m/Saad-Alghamidi/' },
    { name: 'سعود الشريم', path: 'https://surahmp3.com/m/Saoud-Shrim/' },
    { name: 'ياسر الدوسري', path: 'https://surahmp3.com/m/Yasser-Addawsari/' },
]