export const Al9ora2Array = [
  {
    id: 0,
    name: "أحمد الحواشي",
    path: "https://surahmp3.com/m/Ahmad-Alhawashi/",
    riwayat: ["hafs"],
  },
  {
    id: 1,
    name: "أحمد بن علي العجمي",
    path: "https://surahmp3.com/m/Ahmad-Bnali-Alajami/",
    riwayat: ["hafs"],
  },
  {
    id: 2,
    name: "أحمد سعود",
    path: "https://surahmp3.com/m/Ahmed-Saoud/",
    riwayat: ["hafs"],
  },
  {
    id: 3,
    name: "أحمد صابر",
    path: "https://surahmp3.com/m/Ahmed-Saber/",
    riwayat: ["hafs"],
  },
  {
    id: 4,
    name: "أحمد نعينع",
    path: "https://surahmp3.com/m/Ahmed-N3in3/",
    riwayat: ["hafs"],
  },
  {
    id: 5,
    name: "أكرم العلاقمي",
    path: "https://surahmp3.com/m/Akram-Alalakmi/",
    riwayat: ["hafs"],
  },
  {
    id: 6,
    name: "إبراهيم الأخضر",
    path: "https://surahmp3.com/m/Ibrahim-Alakhdar/",
    riwayat: ["hafs"],
  },
  {
    id: 7,
    name: "إبراهيم الجبرين",
    path: "https://surahmp3.com/m/Ibrahim-Aljabrin/",
    riwayat: ["hafs"],
  },
  {
    id: 8,
    name: "ابراهيم العسيري",
    path: "https://surahmp3.com/m/Ibrahim-Alossayri/",
    riwayat: ["hafs"],
  },
  {
    id: 9,
    name: "ادريس أبكر",
    path: "https://surahmp3.com/m/Idriss-Abkar/",
    riwayat: ["hafs"],
  },
  {
    id: 10,
    name: "الحسيني العزازي",
    path: "https://surahmp3.com/m/Alhsini-Al3zazi/",
    riwayat: ["mo3alam"],
  },
  {
    id: 11,
    name: "الزين محمد أحمد",
    path: "https://surahmp3.com/m/Alzain-Mohamed-Ahmed/",
    riwayat: ["hafs"],
  },
  {
    id: 12,
    name: "العشري عمران",
    path: "https://surahmp3.com/m/Alachri-Omran/",
    riwayat: ["hafs"],
  },
  {
    id: 13,
    name: "العيون الكوشي",
    path: "https://surahmp3.com/m/Layoun-Alkouchi/",
    riwayat: ["warsh"],
  },
  {
    id: 14,
    name: "القارئ ياسين",
    path: "https://surahmp3.com/m/Alkari-Yassine/",
    riwayat: ["warsh"],
  },
  {
    id: 15,
    name: "توفيق الصايغ",
    path: "https://surahmp3.com/m/Twfik-Assaygh/",
    riwayat: ["hafs"],
  },
  {
    id: 16,
    name: "جمال شاكر عبدالله",
    path: "https://surahmp3.com/m/Jamal-Chakir-Abdallah/",
    riwayat: ["hafs"],
  },
  {
    id: 17,
    name: "حمد الدغريري",
    path: "https://surahmp3.com/m/Hamad-Adghrizi/",
    riwayat: ["hafs"],
  },
  {
    id: 18,
    name: "خالد الجليل",
    path: "https://surahmp3.com/m/Khakid-Aljalil/",
    riwayat: ["hafs"],
  },
  {
    id: 19,
    name: "خالد القحطاني",
    path: "https://surahmp3.com/m/Khalid-Alkahtani/",
    riwayat: ["hafs"],
  },
  {
    id: 20,
    name: "خالد الوهيبي",
    path: "https://surahmp3.com/m/Khalid-Alwahbi/",
    riwayat: ["hafs"],
  },
  {
    id: 21,
    name: "خالد عبد الكافي",
    path: "https://surahmp3.com/m/Khalid-Abdelkafi/",
    riwayat: ["hafs"],
  },
  {
    id: 22,
    name: "خليفة الطنيجي",
    path: "https://surahmp3.com/m/Khalifa-Atniji/",
    riwayat: ["hafs"],
  },
  {
    id: 23,
    name: "داود حمزة",
    path: "https://surahmp3.com/m/Dawoud-Hamza/",
    riwayat: ["hafs"],
  },
  {
    id: 24,
    name: "رشيد إفراد",
    path: "https://surahmp3.com/m/Rachid-Ifrad/",
    riwayat: ["warsh"],
  },
  {
    id: 25,
    name: "رشيد بلعالية",
    path: "https://surahmp3.com/m/Rachid-Bl3alya/",
    riwayat: ["hafs", "warsh"],
  },
  {
    id: 26,
    name: "زكريا حمامة",
    path: "https://surahmp3.com/m/Zakaria-Hmama//",
    riwayat: ["hafs"],
  },
  {
    id: 27,
    name: "زكي داغستاني",
    path: "https://surahmp3.com/m/Zaki-Daghstani/",
    riwayat: ["hafs"],
  },
  {
    id: 28,
    name: "سامي الحسن",
    path: "https://surahmp3.com/m/Sami-Alhassan/",
    riwayat: ["hafs"],
  },
  {
    id: 29,
    name: "سامي الدوسري",
    path: "https://surahmp3.com/m/Sami-Adawsari/",
    riwayat: ["hafs"],
  },
  {
    id: 30,
    name: "سعد الغامدي",
    path: "https://surahmp3.com/m/Saad-Alghamidi/",
    riwayat: ["hafs"],
  },
  {
    id: 31,
    name: "سعود الشريم",
    path: "https://surahmp3.com/m/Saoud-Shrim/",
    riwayat: ["hafs"],
  },
  {
    id: 32,
    name: "سهل ياسين",
    path: "https://surahmp3.com/m/Sahl-Yassine/",
    riwayat: ["hafs"],
  },
  {
    id: 33,
    name: "سيد رمضان",
    path: "https://surahmp3.com/m/Sayid-Ramadan/",
    riwayat: ["hafs"],
  },
  {
    id: 34,
    name: "شعبان الصياد",
    path: "https://surahmp3.com/m/Chaaban-Assayad/",
    riwayat: ["hafs"],
  },
  {
    id: 35,
    name: "شيخ أبو بكر الشاطري",
    path: "https://surahmp3.com/m/Aboubakr-Achatiri/",
    riwayat: ["hafs"],
  },
  {
    id: 36,
    name: "شيرزاد عبد الرحمن طاهر",
    path: "https://surahmp3.com/m/Chirzad-Abdrahman-Tahir/",
    riwayat: ["hafs"],
  },
  {
    id: 37,
    name: "صابر عبد الحكم",
    path: "https://surahmp3.com/m/Saber-Abdelhakam/",
    riwayat: ["hafs"],
  },
  {
    id: 38,
    name: "صالح آل طالب",
    path: "https://surahmp3.com/m/Salih-Altaleb/",
    riwayat: ["hafs"],
  },
  {
    id: 39,
    name: "صالح الصاهود",
    path: "https://surahmp3.com/m/Salih-Assahod/",
    riwayat: ["hafs"],
  },
  {
    id: 40,
    name: "صالح الهبدان",
    path: "https://surahmp3.com/m/Salih-Alhabdan/",
    riwayat: ["hafs"],
  },
  {
    id: 41,
    name: "صلاح البدير",
    path: "https://surahmp3.com/m/Salah-Albdir/",
    riwayat: ["hafs"],
  },
  {
    id: 42,
    name: "صلاح الهاشم",
    path: "https://surahmp3.com/m/Salah-Alhachim/",
    riwayat: ["hafs", "9alon"],
  },
  {
    id: 43,
    name: "صلاح بو خاطر",
    path: "https://surahmp3.com/m/Salah-Boukhatr/",
    riwayat: ["hafs"],
  },
  {
    id: 44,
    name: "عادل ريان",
    path: "https://surahmp3.com/m/Adil-Rayan/",
    riwayat: ["hafs"],
  },
  {
    id: 45,
    name: "عبد البارئ الثبيتي",
    path: "https://surahmp3.com/m/Abdlbari-Tbiti/",
    riwayat: ["hafs"],
  },
  {
    id: 46,
    name: "عبد البارئ محمد",
    path: "https://surahmp3.com/m/Abdlbari-Mohamed/",
    riwayat: ["hafs", "mo3alam"],
  },
  {
    id: 47,
    name: "عبد الباسط عبدالصمد",
    path: "https://surahmp3.com/m/Abdlbast-Abdsamad/",
    riwayat: ["hafs", "warsh", "mojawad"],
  },
  {
    id: 48,
    name: "عبد الرشيد صوفي",
    path: "https://surahmp3.com/m/Abdrachid-Sofi/",
    riwayat: ["hafs", "khalaf", "sousi"],
  },
  {
    id: 49,
    name: "عبد العزيز الأحمد",
    path: "https://surahmp3.com/m/Abdla3ziz-Alahmad/",
    riwayat: ["hafs"],
  },
  {
    id: 50,
    name: "عبد العزيز الزهراني",
    path: "https://surahmp3.com/m/Abdlaziz-Azahrani/",
    riwayat: ["hafs"],
  },
  {
    id: 51,
    name: "عبد الله البريمي",
    path: "https://surahmp3.com/m/Abdlah-Albrimi/",
    riwayat: ["hafs"],
  },
  {
    id: 52,
    name: "عبد الله البعيجان",
    path: "https://surahmp3.com/m/Abdlah-Alb3ijan/",
    riwayat: ["hafs"],
  },
  {
    id: 53,
    name: "عبد الله المطرود",
    path: "https://surahmp3.com/m/Abdlah-Almtrod/",
    riwayat: ["hafs"],
  },
  {
    id: 54,
    name: "عبد الله بصفر",
    path: "https://surahmp3.com/m/Abdelah-Bsfr/",
    riwayat: ["hafs"],
  },
  {
    id: 55,
    name: "عبد الله خياط",
    path: "https://surahmp3.com/m/Abdlah-Khyat/",
    riwayat: ["hafs"],
  },
  {
    id: 56,
    name: "عبد الله عواد الجهني",
    path: "https://surahmp3.com/m/Abdlah-Owad-Aljahni/",
    riwayat: ["hafs"],
  },
  {
    id: 57,
    name: "عبد الله غيلان",
    path: "https://surahmp3.com/m/Abdlah-Ghilan/",
    riwayat: ["hafs"],
  },
  {
    id: 58,
    name: "عبد المحسن الحارثي",
    path: "https://surahmp3.com/m/Abdlmohsin-Alhariti/",
    riwayat: ["hafs"],
  },
  {
    id: 59,
    name: "عبد المحسن العبيكان",
    path: "https://surahmp3.com/m/Abdlmohsin-Al3bikan/",
    riwayat: ["hafs"],
  },
  {
    id: 60,
    name: "عبد المحسن العسكر",
    path: "https://surahmp3.com/m/Abdlmohsin-Alaskr/",
    riwayat: ["hafs"],
  },
  {
    id: 61,
    name: "عبد المحسن القاسم",
    path: "https://surahmp3.com/m/Abdlmohsin-Alkasm/",
    riwayat: ["hafs"],
  },
  {
    id: 62,
    name: "عبد الهادي أحمد كناكري",
    path: "https://surahmp3.com/m/Abdlhadi-Ahmad-Knakri/",
    riwayat: ["hafs"],
  },
  {
    id: 63,
    name: "عبد الودود حنيف",
    path: "https://surahmp3.com/m/Abdalwadod-Hanif/",
    riwayat: ["hafs"],
  },
  {
    id: 64,
    name: "عبد الولي الأركاني",
    path: "https://surahmp3.com/m/Abdlwali-Alarkari/",
    riwayat: ["hafs"],
  },
  {
    id: 65,
    name: "عبدالرحمن السديس",
    path: "https://surahmp3.com/m/Abdrahman-Sudaysi/",
    riwayat: ["hafs"],
  },
  {
    id: 66,
    name: "علي أبو هاشم",
    path: "https://surahmp3.com/m/Ali-Abouhachim/",
    riwayat: ["hafs"],
  },
  {
    id: 67,
    name: "علي بن عبد الرحمن الحذيفي",
    path: "https://surahmp3.com/m/Ali-Bn-Abdrahman-Alhodayfi/",
    riwayat: ["hafs", "9alon"],
  },
  {
    id: 68,
    name: "علي جابر",
    path: "https://surahmp3.com/m/Ali-Jabir/",
    riwayat: ["hafs"],
  },
  {
    id: 69,
    name: "علي حجاج السويسي",
    path: "https://surahmp3.com/m/Ali-Hajaj-Aswissi/",
    riwayat: ["hafs"],
  },
  {
    id: 70,
    name: "عماد زهير حافظ",
    path: "https://surahmp3.com/m/Imad-Zohir-Hafid/",
    riwayat: ["hafs"],
  },
  {
    id: 71,
    name: "عمر القزابري",
    path: "https://surahmp3.com/m/Omar-Alkzabri/",
    riwayat: ["warsh"],
  },
  {
    id: 72,
    name: "فارس عباد",
    path: "https://surahmp3.com/m/Faris-Abad/",
    riwayat: ["hafs"],
  },
  {
    id: 73,
    name: "فهد العتيبي",
    path: "https://surahmp3.com/m/Fahd-Alotaybi/",
    riwayat: ["hafs"],
  },
  {
    id: 74,
    name: "فهد الكندري",
    path: "https://surahmp3.com/m/Fahd-Alkndri/",
    riwayat: ["hafs"],
  },
  {
    id: 75,
    name: "فواز الكعبي",
    path: "https://surahmp3.com/m/Fawaz-Alka3bi/",
    riwayat: ["hafs"],
  },
  {
    id: 76,
    name: "لافي العوني",
    path: "https://surahmp3.com/m/Lafi-Alawni/",
    riwayat: ["hafs"],
  },
  {
    id: 77,
    name: "ماجد العنزي",
    path: "https://surahmp3.com/m/Majid-Al3nzi/",
    riwayat: ["hafs"],
  },
  {
    id: 78,
    name: "مالك شيبة الحمد",
    path: "https://surahmp3.com/m/Malik-Chayba-Alhmd/",
    riwayat: ["hafs"],
  },
  {
    id: 79,
    name: "ماهر المعيقلي",
    path: "https://surahmp3.com/m/Maher-Alm3i9li/",
    riwayat: ["hafs", "mo3alam"],
  },
  {
    id: 80,
    name: "محمد أيوب",
    path: "https://surahmp3.com/m/Mohamed-Ayoub/",
    riwayat: ["hafs"],
  },
  {
    id: 81,
    name: "محمد الأيراوي",
    path: "https://surahmp3.com/m/Mohamed-Alirawi/",
    riwayat: ["warsh"],
  },
  {
    id: 82,
    name: "محمد البراك",
    path: "https://surahmp3.com/m/Mohamed-Abarak/",
    riwayat: ["hafs"],
  },
  {
    id: 83,
    name: "محمد الطبلاوي",
    path: "https://surahmp3.com/m/Mohamed-Atablawi/",
    riwayat: ["hafs"],
  },
  {
    id: 84,
    name: "محمد اللحيدان",
    path: "https://surahmp3.com/m/Mohamed-Alahidan/",
    riwayat: ["hafs"],
  },
  {
    id: 85,
    name: "محمد المحيسني",
    path: "https://surahmp3.com/m/Mohamed-Almhisni/",
    riwayat: ["hafs"],
  },
  {
    id: 86,
    name: "محمد جبريل",
    path: "https://surahmp3.com/m/Mohamed-Jibril/",
    riwayat: ["hafs"],
  },
  {
    id: 87,
    name: "محمد صالح عالم شاه",
    path: "https://surahmp3.com/m/Mohamed-Salih-3alim-Chah/",
    riwayat: ["hafs"],
  },
  {
    id: 88,
    name: "محمد صديق المنشاوي",
    path: "https://surahmp3.com/m/Mohamed-Sidi9-Almnchawi/",
    riwayat: ["hafs", "mo3alam", "mojawad"],
  },
  {
    id: 89,
    name: "محمد عبد الحكيم بن سعيد",
    path: "https://surahmp3.com/m/Mohamed-Abdlhakim-Bnsa3id/",
    riwayat: ["bzri9onbol", "dawrikisa2i"],
  },
  {
    id: 90,
    name: "محمد عبد الكريم",
    path: "https://surahmp3.com/m/Mohamed-Abdlkrim/",
    riwayat: ["hafs", "warsh"],
  },
  {
    id: 91,
    name: "محمود خليل الحصري",
    path: "https://surahmp3.com/m/Mahmoud-Khalil-Alhossari/",
    riwayat: ["warsh", "hafs", "mojawad"],
  },
  {
    id: 92,
    name: "محمود علي البنا",
    path: "https://surahmp3.com/m/Mohmod-Ali-Albana/",
    riwayat: ["hafs", "mojawad"],
  },
  {
    id: 93,
    name: "مشاري العفاسي",
    path: "https://surahmp3.com/m/Mchari-Al3fassi/",
    riwayat: ["hafs", "dawrikisa2i"],
  },
  {
    id: 94,
    name: "ناصر القطامي",
    path: "https://surahmp3.com/m/Nassir-Al9tami/",
    riwayat: ["hafs"],
  },
  {
    id: 95,
    name: "نبيل الرفاعي",
    path: "https://surahmp3.com/m/Nabil-Arifa3i/",
    riwayat: ["hafs"],
  },
  {
    id: 96,
    name: "نعمة الحسان",
    path: "https://surahmp3.com/m/Ni3mat-Alhassan/",
    riwayat: ["hafs"],
  },
  {
    id: 97,
    name: "هاني الرفاعي",
    path: "https://surahmp3.com/m/Hani-Arifa3i/",
    riwayat: ["hafs"],
  },
  {
    id: 98,
    name: "وليد الدليمي",
    path: "https://surahmp3.com/m/Walid-Adlimi/",
    riwayat: ["hafs"],
  },
  {
    id: 99,
    name: "وليد النائحي",
    path: "https://surahmp3.com/m/Walid-Ana2i7i/",
    riwayat: ["9alon"],
  },
  {
    id: 100,
    name: "ياسر الدوسري",
    path: "https://surahmp3.com/m/Yassir-Adawsari/",
    riwayat: ["hafs"],
  },
  {
    id: 101,
    name: "ياسر الفيلكاوي",
    path: "https://surahmp3.com/m/Yassir-Alfilikawi/",
    riwayat: ["hafs"],
  },
  {
    id: 102,
    name: "ياسر القرشي",
    path: "https://surahmp3.com/m/Yassine-Al9orachi/",
    riwayat: ["hafs"],
  },
  {
    id: 103,
    name: "ياسر المزروعي",
    path: "https://surahmp3.com/m/Yassir-Almzro3i/",
    riwayat: ["hafs"],
  },
  {
    id: 104,
    name: "يحيى حوا",
    path: "https://surahmp3.com/m/Yahya-Hawa/",
    riwayat: ["hafs"],
  },
  {
    id: 105,
    name: "يوسف الشويعي",
    path: "https://surahmp3.com/m/Youssef-Achwi3i/",
    riwayat: ["hafs"],
  },
];
